name: Build and Push Image
on: [ push ]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      run: docker build -t test-app .
      
    - name: Install BuildX
      run: git clone git://github.com/docker/buildx && cd buildx && make install
          
    - name: Login to GitHub Package Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
        
    - name: Retag Image
      run: docker tag test-app ghcr.io/${{ github.repository_owner }}/test-app
      
    - name: Push Image to Registry
      run: docker push ghcr.io/${{ github.repository_owner }}/test-app
